x = input("이름을 입력하세요: ")
y = input("학번을 입력하세요: ")
z = input("학과를 입력하세요: ")
a = input("학교를 입력하세요: ")
b = input("학년을 입력하세요: ")
print("\n<출력>")
print("이름 : "+ x)
print("학번: "+y)
print("학과: "+z)
print("학교: "+a)
print("학년: "+b)

